# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-14082-ramachine/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg400-3
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include /home/taylor/Documents/code/spgd/fpga_projects/SPGD/tmp/SPGD/SPGD.srcs/sources_1/bd/system/ipshared/ec67/hdl -define TOOL_VIVADO {
      /opt/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /opt/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include /home/taylor/Documents/code/spgd/fpga_projects/SPGD/tmp/SPGD/SPGD.srcs/sources_1/bd/system/ipshared/ec67/hdl -define TOOL_VIVADO {
      ./.Xil/Vivado-14082-ramachine/realtime/system_ADC_REG_0_stub.v
      ./.Xil/Vivado-14082-ramachine/realtime/system_LED_CONTROLLER_0_stub.v
      ./.Xil/Vivado-14082-ramachine/realtime/system_ADC_DAC_LOOP_0_stub.v
      ./.Xil/Vivado-14082-ramachine/realtime/system_processing_system7_0_0_stub.v
      ./.Xil/Vivado-14082-ramachine/realtime/system_axi_gpio_0_0_stub.v
      ./.Xil/Vivado-14082-ramachine/realtime/system_rst_ps7_0_50M_0_stub.v
      ./.Xil/Vivado-14082-ramachine/realtime/system_util_ds_buf_0_0_stub.v
      ./.Xil/Vivado-14082-ramachine/realtime/system_util_ds_buf_1_0_stub.v
      ./.Xil/Vivado-14082-ramachine/realtime/system_auto_pc_0_stub.v
      /home/taylor/Documents/code/spgd/fpga_projects/SPGD/src/ADC_REG.v
      /home/taylor/Documents/code/spgd/fpga_projects/SPGD/src/LED_CONTROLLER.v
      /home/taylor/Documents/code/spgd/fpga_projects/SPGD/src/ADC_AVERAGE.v
      /home/taylor/Documents/code/spgd/fpga_projects/SPGD/src/DAC_offset_to_twos.v
      /home/taylor/Documents/code/spgd/fpga_projects/SPGD/src/FSM.v
      /home/taylor/Documents/code/spgd/fpga_projects/SPGD/src/gen_adder.v
      /home/taylor/Documents/code/spgd/fpga_projects/SPGD/src/gen_counter.v
      /home/taylor/Documents/code/spgd/fpga_projects/SPGD/src/gen_mult.v
      /home/taylor/Documents/code/spgd/fpga_projects/SPGD/src/gen_padder.v
      /home/taylor/Documents/code/spgd/fpga_projects/SPGD/src/twos_to_ADC_offset.v
      /home/taylor/Documents/code/spgd/fpga_projects/SPGD/src/ADC_DAC_LOOP.v
      /home/taylor/Documents/code/spgd/fpga_projects/SPGD/tmp/SPGD/SPGD.srcs/sources_1/bd/system/ipshared/442e/hdl/xlconcat_v2_1_vl_rfs.v
      /home/taylor/Documents/code/spgd/fpga_projects/SPGD/tmp/SPGD/SPGD.srcs/sources_1/bd/system/ip/system_xlconcat_0_0/synth/system_xlconcat_0_0.v
      /home/taylor/Documents/code/spgd/fpga_projects/SPGD/tmp/SPGD/SPGD.srcs/sources_1/bd/system/synth/system.v
      /home/taylor/Documents/code/spgd/fpga_projects/SPGD/tmp/SPGD/SPGD.srcs/sources_1/bd/system/hdl/system_wrapper.v
    }
      rt::read_vhdl -lib xpm /opt/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top system_wrapper
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-14082-ramachine/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
