#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Jul 14 17:35:01 EDT 2022
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 6e71d1509e0e4207ae3dfb78e4d0e008 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot ADC_AVERAGE_tb_behav xil_defaultlib.ADC_AVERAGE_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 6e71d1509e0e4207ae3dfb78e4d0e008 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot ADC_AVERAGE_tb_behav xil_defaultlib.ADC_AVERAGE_tb xil_defaultlib.glbl -log elaborate.log

