#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jul 14 17:35:03 EDT 2022
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim ADC_AVERAGE_tb_behav -key {Behavioral:sim_1:Functional:ADC_AVERAGE_tb} -tclbatch ADC_AVERAGE_tb.tcl -view /home/taylor/Documents/GH/SPGD/fpga_projects/SPGD/tmp/SPGD/ADC_AVERAGE_tb_behav.wcfg -log simulate.log"
xsim ADC_AVERAGE_tb_behav -key {Behavioral:sim_1:Functional:ADC_AVERAGE_tb} -tclbatch ADC_AVERAGE_tb.tcl -view /home/taylor/Documents/GH/SPGD/fpga_projects/SPGD/tmp/SPGD/ADC_AVERAGE_tb_behav.wcfg -log simulate.log

