# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/taylor/Documents/GH/SPGD/fpga_projects/SPGD/cfg/ports.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_ADC_REG_0/system_ADC_REG_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ADC_REG_0 || ORIG_REF_NAME==system_ADC_REG_0} -quiet] -quiet

# IP: bd/system/ip/system_LED_CONTROLLER_0/system_LED_CONTROLLER_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LED_CONTROLLER_0 || ORIG_REF_NAME==system_LED_CONTROLLER_0} -quiet] -quiet

# IP: bd/system/ip/system_ADC_DAC_LOOP_0/system_ADC_DAC_LOOP_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ADC_DAC_LOOP_0 || ORIG_REF_NAME==system_ADC_DAC_LOOP_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cfg_register_0/system_axi_cfg_register_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_cfg_register_0 || ORIG_REF_NAME==system_axi_cfg_register_0} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_50M_0/system_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_50M_0 || ORIG_REF_NAME==system_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_0_0/system_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ds_buf_0_0 || ORIG_REF_NAME==system_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ds_buf_1_0 || ORIG_REF_NAME==system_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: bd/system/system_ooc.xdc
